# -*- coding: utf-8 -*-
"""ejercicio_en_clase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eF6hVqJTwX-9da3aYTscGZVHru-UzDw

# Alexis Chavez Juarez A01657486
## Mapas de calor y boxplots
"""

import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('twitter_dataset.csv')
df

plt.boxplot([df["Retweets"]], patch_artist=True, labels=["Retweets promedio"])

plt.boxplot([df["Likes"]], patch_artist=True, labels=["Retweets promedio"])

sns.boxplot(data=df, y="Retweets", x="Username")

sns.boxplot(data=df, y="Retweets", x="Likes")

sns.boxplot(data=df, y="Retweets", x="Timestamp")

ydf=df[df["Likes"]<=20]
ydf=ydf.groupby(["Likes"]).sum()
ydf=ydf.sort_values("Retweets",ascending=False)
sns.barplot(data=ydf.head(5),y="Retweets", x="Likes")

dfcor=df[['Retweets','Likes','Tweet_ID']].corr()
sns.heatmap(dfcor,cmap="PuBu")

sns.histplot(data=df,x="Likes")

"""## Resolución de preguntas:
### ¿Hay alguna variable que no aporta información?
Sí, hay 2 variables que no aportan información porque no se pueden comparar numericamente, las cuales son el Tweet_ID y el texto del tweet. El tweet ID se puede sacar sumándole uno al índice de cada tweet, entonces no es de ningún valor, solo es informativo si se quiere saber que tweet es. Y por otro lado, el texto del tweet no lo estamos comparando, entonces no es necesario en este caso.

### Si tuvieras que eliminar variables, ¿cuáles quitarías y por qué?
Cómo se menciono en la pregunta anterior, quitaría el texto del tweet, el tweet_ID y dependiendo que se quiera comparar, también el timestamp. Por ejemplo, en el mapa de calor no se puede comparar, pero en las cajas y bigotes sí.
### ¿Existen variables que tengan datos extraños?
Considero que en este caso, no hay ninguna variable con valor extraño, solo que son difíciles de comparar.
### Si comparas las variables, ¿todas están en rangos similares? ¿Crees que esto afecte?
Las únicas que se pueden comparar son tweet likes y retweets. Entonces si están en rangos similares. Excepto las demás variables que no tienen ninguna relación ni valor similar.
### ¿Puedes encontrar grupos qué se parezcan? ¿Qué grupos son estos?

Los grupos numéricos y los grupos no numéricos. Que por un lado son: tweet_ID, likes y retweets. Y en no numéricos son username, text y timestamp.

Link de github: [link](https://github.com/AlexisChJ/arteDeLaAnalitica.git)
"""