# -*- coding: utf-8 -*-
"""ObtencionEstadisticasDescriptivasAlexis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFmRY0aw_IZ1pIpNQ7mELh5j3U-SU5Zo

# Alexis Chávez Juárez Obtención de Estadísticas Descriptivas
"""

import numpy as np
import pandas as pd
import csv

aguacates = pd.read_csv('avocado_full.csv')
datos_newyork = aguacates[aguacates['region'] == 'NewYork']
datos_california = aguacates[aguacates['region'] == 'California']
datos_charlotte = aguacates[aguacates['region'] == 'Charlotte']

"""Datos por cada ciudad"""

#datos_newyork
total_bags_ny = datos_newyork['Total Bags'].sum()
print("La producción total de New York es de: ",total_bags_ny)
promedio = datos_newyork['Total Bags'].mean()
print("El promedio es ",promedio)
desv = datos_newyork['Total Bags'].std()
print("La desviación estándar es es ",desv)

small = ((datos_newyork['Small Bags'].sum())*100)/total_bags_ny
print("El % de small es de: ", small)
large = ((datos_newyork['Large Bags'].sum())*100)/total_bags_ny
print("El % de large es de: ", large)
xlarge = ((datos_newyork['XLarge Bags'].sum())*100)/total_bags_ny
print("El % de xlarge es de: ", xlarge)

"""Con los datos obtenidos, se puede inferir que el 85% de las bolsas son pequeñas, por lo que deberían de darle prioridad la empresa en ese tipo de bolsas en New York. Además, el porcentaje de xlarg es de 0.52% por lo que no significa un porcentaje grande que ayude mucho a las ventas. Y el porcentaje de large es de 13%, que puede tener un potencial crecimeinto dado que no es un porcentaje grande pero si chico."""

#datos_california
total_bags_cal = datos_california['Total Bags'].sum()
print("La producción total de California es de: ",total_bags_cal)
promedio = datos_california['Total Bags'].mean()
print("El promedio es ",promedio)
desv = datos_california['Total Bags'].std()
print("La desviación estándar es es ",desv)

small = ((datos_california['Small Bags'].sum())*100)/total_bags_cal
print("El % de small es de: ", small)
large = ((datos_california['Large Bags'].sum())*100)/total_bags_cal
print("El % de large es de: ", large)
xlarge = ((datos_california['XLarge Bags'].sum())*100)/total_bags_cal
print("El % de xlarge es de: ", xlarge)

"""Con los datos obtenidos, se puede obsrvar que el porcentaje de bolsas pequeñas es de 92%, por lo que los clientes prefieren comprar bolsas de ese tamaño y no conviene invertir en bolsas de mayor tamaño. Con esto, el porcentaje de bolsas grandes y extra grandes son de 4.99% y 2.13% respectivamente. La diferencia es muy grande y en California no se debería de dar mucha importancia en las bolsas de mayor tamaño."""

#datos_charlotte
total_bags_char = datos_charlotte['Total Bags'].sum()
print("La producción total de Charlottees de: ",total_bags_char)
promedio = datos_charlotte['Total Bags'].mean()
print("El promedio es ",promedio)
desv = datos_charlotte['Total Bags'].std()
print("La desviación estándar es es ",desv)

small = ((datos_charlotte['Small Bags'].sum())*100)/total_bags_char
print("El % de small es de: ", small)
large = ((datos_charlotte['Large Bags'].sum())*100)/total_bags_char
print("El % de large es de: ", large)
xlarge = ((datos_charlotte['XLarge Bags'].sum())*100)/total_bags_char
print("El % de xlarge es de: ", xlarge)

"""Con los datos de Charlotte, sucede algo muy similar con lo de New York. Las bolsas pequeñas ocupan la mayor cuota de mercado y las grandes tienen un gran potencial. Sin embargo, las extra grandes no ocupan ni el 1%, por lo que es mejor enfocarse en las grandes que en las extragrandes.

## Conclusiones generales

Con los datos obtenidos se puede inferir que el estado con mayor venta de bolsas de agacate es California, casi duplicando las ventas de Charlotte y New york. Asimismo, las bolsas de mayor tamaño no son tan compradas por los clientes, pero las pequeñas son muy bien vendidas. También, el tamaño de bolsa extra grande representa un porcentaje insignificante en las ventas, por lo que convendría no invertirle más a ese tamaño.
"""