# -*- coding: utf-8 -*-
"""Patrones con K-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZAGslrCyo5l4PbAph3Gq9sCtMI0SsiT

# Alexis Chavez Juarez A01657486
## Mapas de calor y boxplots
"""

import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('twitter_dataset.csv')
df

plt.boxplot([df["Retweets"]], patch_artist=True, labels=["Retweets promedio"])

plt.boxplot([df["Likes"]], patch_artist=True, labels=["Retweets promedio"])

sns.boxplot(data=df, y="Retweets", x="Username")

sns.boxplot(data=df, y="Retweets", x="Likes")

sns.boxplot(data=df, y="Retweets", x="Timestamp")

ydf=df[df["Likes"]<=20]
ydf=ydf.groupby(["Likes"]).sum()
ydf=ydf.sort_values("Retweets",ascending=False)
sns.barplot(data=ydf.head(5),y="Retweets", x="Likes")

dfcor=df[['Retweets','Likes','Tweet_ID']].corr()
sns.heatmap(dfcor,cmap="PuBu")

sns.histplot(data=df,x="Likes")

df[['Retweets','Likes','Tweet_ID']].corr()

df.plot.scatter(x='Likes' , y='Retweets')

from sklearn.cluster import KMeans

X=df[['Likes','Retweets']]
X

m=KMeans(7)
m.fit(X)
X["cl"]=m.labels_
X.plot.scatter(x='Likes' , y='Retweets',c="cl",colormap='gist_rainbow')

centros = m.cluster_centers_
print("Centros de los clusters:")
print(centros)

"""¿Crees que estos centros puedan ser representativos de los datos? ¿Por qué?

Sí, porque da difersas "combinaciones" y relaciones entre likes y retweets.

¿Cómo obtuviste el valor de k a usar?
Con varias pruebas, con valores con k, pude ver que 7 es donde se representa mejor los valores y pone los colores en grupos más establecidos.

¿Los centros serían más representativos si usaras un valor más alto? ¿Más bajo?

De hecho, creo que si se usara un valor más bajo, Ya que la relación en este caso de likes y retweets es muy buena, pero estos datos son grandes, y si se usa un valor bajo, puede ayudarnos a tener un mejor análisis.

¿Qué distancia tienen los centros entre sí? ¿Hay alguno que este muy cercano a otros?

¿Qué pasaría con los centros si tuviéramos muchos outliers en el análisis de cajas y bigotes?
Los centros pueden verse atraídos a los outliers, lo que puede hacer que los centros sean sesgados y no sea un buen análisis el que se realiza.

¿Qué puedes decir de los datos basándose en los centros?
 Algunos clusters tienen alta cantidad de likes pero poca de retweets, esto se puede deber a que una persona es famosa/conocida pero su contenido no es tan importante como que la gente lo repostee. Y por otro lado, si sucede lo contrario, puede que la persona sea alguien poco conocido pero si el tweet que puso es muy relevante, puede generar que la gente lo retweetee.

Link de github: [link](https://github.com/AlexisChJ/arteDeLaAnalitica.git)
"""